pegged/dev/introspection.d

Fix problems in the introspection module, and add an overload.

Grammar Introspection

---

pegged/examples/peggedgrammar.d
pegged/grammar.d
pegged/parser.d
pegged/peg.d

Hi Philippe,
This implements the suggestion made by Bit-Doctor in #119. It supports unicode.
Hope you like it,
Bastiaan.

PEG extension for case insensitive literals.

---

makefile

Although I am having difficulties testing this, I think this is necessary if I read #172 right.

Add introspection.d to the Makefile.

---

README.md

Should it be added to features instead?

Remove left-recursion from limitations.

---

pegged/peg.d

Is this enough to close PhilippeSigaud/Pegged#183?

Improve readability of failure messages.

---

pegged/peg.d

There's no problem with format with \r, i investigated at dpaste and it seems like their problem.

Better special characters escaping

---

pegged/peg.d
pegged/tohtml.d

Few improvements to HTML output.

---

pegged/examples/extended_pascal/source/app.d
pegged/peg.d

1. Improved position indication.
2. Extended support for trace conditions.

Improvements to the tracer.

---

pegged/examples/extended_pascal/example.html

Not sure this'll work, it'd be nice.

Add generated HTML, for inclusion in the Wiki through rawgit.com.

---

pegged/tohtml.d

I've been concatenating strings like a noob. Thanks to profiling, this PR prevents a boatload of allocations, bringing my test parse time down from 17s to under 5s, when generating HTML output. As a test, I commented out all output generation, which saved about half a second. So the parsing itself takes about 4.5 seconds and generating and writing the 24 MB HTML file half a second (on an SSD).
The bad news: generating text output (34 MB in size, via `parseTree.toString.toFile`) takes 28 seconds. So the problem is even bigger there. Arguably, this isn't that important as these massive text files are rather useless anyway, but it is a nice illustration of how a few string concatenations in the wrong place can bring down performance.

[Performance] Prevent unnecessary string concatenation in toHTML.

---

pegged/tohtml.d

Less click, prevent the tendinitis.

add options to expand the html tree, close #228

---

pegged/peg.d

+ Also, its `@safe` for now.
+ Check the input to the `null`.
+ Some tests (CT, `@safe`, `null`.)

Now, the internal function stringified is able to work at Compile-Time.

---

pegged/tohtml.d

Handle matches that start with a new line.

---

.travis.yml
ci.sh
scripts/core-dump.sh

Travis config and Shell script to execute test on a CI server

---

pegged/peg.d

A lot of template bloat was being generated by having map, filter and
countUntil inside the 'and' and 'or' templates.
By simply moving them outside compilation speed and memory is back to normal
again.

Fix #272 by moving template code around

---

appveyor.yml
ci.bat

Config for appveyor, so can run the unit tests on a windows enviroment. Based on based on https://github.com/atilaneves/unit-threaded appveyor configuration

Initial appveyor config , based on unit-threaded repository

---

.editorconfig

Proposed editorconfig 

---

.editorconfig
.gitignore
pegged/dynamic/peg.d
pegged/examples/c.d
pegged/examples/extended_pascal/source/epgrammar.d
pegged/examples/extended_pascal/source/make.d
pegged/examples/oberon2.d
pegged/examples/pattern.d
pegged/examples/testergrammar.d
pegged/grammar.d
pegged/parser.d
pegged/peg.d

This should finish issue #277 
Also, I modernizes/cleans the gitignore file and tweaked the .editorconfig to control YAML and BAT files.

Normalize indentation and trailing spaces

---

.travis.yml

Removes travis config file warnings

Update to remove warnings

---

pegged/peg.d

Signed-off-by: Luís Ferreira <luis.ferreira@weka.io>
---
I believe this is either a phobos or a compiler issue on scope inference. Documentation/source code guarantees it copies the data, so no need to write an extra `.dup`/`.idup`, just trust it doesn't escape a reference.

chore(peg): make it compilable under -dip1000 flag

---

pegged/peg.d

@ljmf00-wekaio as discussed in #322 , please review the changes

refactor(peg): ease dip1000 changes
