- pegged/grammar.d
This is a bit of a bummer. Grammars with hidden left-recursion can be processed and some input will be matched correctly, but it seems that this is input that also would have been matched if the grammar were rewritten to take the hiding optional out of the recursive cycle (thus describing a different language). Input that really depends on hidden left-recursion will not be matched currently.
The out-commented assert in this test is an example of valid but failing input. I have described the mechanics of this in my message to Nicolas Laurent, https://github.com/norswap/autumn_dev/issues/1.
I hope someone smarter than me will see a solution, but I have a feeling it won't be possible to support in linear time, and probably add a lot of complexity...
Still there is the possibility that I have …
> About hidden left-recursion

- pegged/dev/introspection.d
Man, did I have to concentrate on this one. But satisfying once it finally works.
I'll be using the `cycle` array later on to place the wrapping code around select left-recursive expressions in grammar.d.
> Fixes #166.

- pegged/dev/introspection.d
- pegged/grammar.d
Hi Philippe,
This properly supports hidden left-recursion, and also adds support for left-recursion in memoizing parsers. As far as code is concerned I think we are pretty much there -- I don't expect much changes after this. What could still be added is control over left/right associativity, but I plan to play with this first to see if I need it.
What I couldn't get to work is support for left-recursion at compile-time due to the error "cannot read static variable seed at compile time". I don't really understand why, but I noticed that you are not using memo at compile time either. So I figure I am in good company. Nevertheless, when left-recursion is detected to occur at compile time, compilation stops with an assertion error and explanation.
Parse speed for non-left-recursive rules …
> Left recursion

- pegged/grammar.d
This reverses a change I introduced that has since become obsolete.
> Conditional import of typecons.

- pegged/peg.d
To address my need to see what's happening during a parse, and understand why a certain grammar fails on a particular input, I added optional logging to `peg.d`. I used `version` for two reasons: to not introduce overhead in production parsers and because `std.experimental.logger` is still experimental. The output contains the actual parser code and so is not always easy to read, and I have difficulties getting rid of the time stamps that the log gets peppered with, but it nevertheless has great value when you need it. The down-side of using `version` is that it only works when `peg.d` is part of the compiled files.
Logging is initially off because a decently sized grammar and input can easily generate tens of thousands of log messages, when memoization is off I have seen log files of …
> Support for tracing a parse using std.experimental.logger.

- pegged/dev/README.md
- pegged/grammar.d
- pegged/parser.d
D is awesome.
See the commit messages for explanations. The main intelligence is in `grammar.d` lines 298--317 and 871--875. Unitest on line 2738.
The downside is that when `parser.d` is regenerated it gets many lines of no-op code. These could be prevented if we do the scanning of composition in an introspective analysis, but I don't know whether it would make any practical difference. The extra calls are seldom executed.
> A solution to #162

- pegged/grammar.d
Calls to rules can nest, therefore blocking and unblocking needs to be balanced. This causes the static block counters to be empty after a successful parse, which is good. Nevertheless, a failed parse could leave an unclean state behind, which is now cleaned up in forgetMemo().
> Fix blocking of memoization.

- pegged/tohtml.d
Ever had the problem that `writeln(parseTree)` produces unmanageable amounts of output? Try `toHTML(parseTree, "output.html")` instead! Have a look at [this example output](http://output.jsbin.com/xuvolemiqe). Features expandable tree view and mouse-over matches.
Currently [supported browsers](http://www.w3schools.com/tags/tag_details.asp): Chrome, Safari & Opera.
> New module for presenting a parse tree in HTML.

- package.json
- pegged/examples/extended_pascal/dub.json
- pegged/examples/extended_pascal/source/app.d
- pegged/peg.d
Fixes deprecation error in peg.d for `version(tracer)`.
I am new to dub configurations, I had to introduce a "default" configuration to prevent the "tracer" option to be automatically selected.
> Tracer: example, dub option, compile fix.

- pegged/peg.d
While incrementing `i`, we would first see `[...]\r` and count a new line. Then we would see `[...]\r\n` and count it again.
This change also causes a significant speedup in the tracer!
> Prevent position() from counting DOS line endings twice.

- pegged/examples/peggedgrammar.d
- pegged/grammar.d
- pegged/introspection.d
- pegged/parser.d
- pegged/peg.d
The `longest_match!()` parser is like the `or!()` parser, except that all rules are tried and the one producing the longest match is taken. I have extended the PEG grammar to let `|` denote the longest match choice operator, besides the standard `/` prioritised choice. Unfortunately, the `Expression*` rules in `peggedgrammar.d` have become a tad convoluted; at first I used negative lookahead, but this I think is better. Alternatively, I could have used `Expression <- Expression | LongestExpression`.
I hope you think this is worth it. With this change I _am_ able to parse a complete EP source file that is currently in production, with non-standard language extensions. The `epgrammar.d` changes for this I will commit later. You may bump the version before or after that, but maybe let me …
> Implement longest match parser. Closes PhilippeSigaud/Pegged#218.

- pegged/examples/extended_pascal/source/epgrammar.d
- pegged/examples/extended_pascal/source/make.d
Grammar changes that lead to the successful parse of a 200KiB real-life Prospero Extended Pascal file.
You were asking about performance: The parse takes 13 minutes. The generated HTML file is close to 24 MiB large. I have never traced all of it, because my trace files passed the 1GiB mark and I am short on disk space.
So, it's not fast. To be fair, this grammar is bloated and could probably be optimised heavily for speed. But I like to stay close to the text of the standard, and it is not too slow for my application.
I have been delayed with the documentation that I promised, because it came to me that trying the rules in `longest_match` could possibly be parallelised, and how cool would that be? I almost have it working, but at least on OS X I get a bus error, possibly because of the …
> EP grammar changes.

- pegged/grammar.d
This brings the parsing of a sample Extended Pascal file down from 13 minutes to 17 seconds. The mistake was not to assign the result of std.algorithm.mutation.remove, which caused an array to grow to a massive size and memoization to never be reenabled. (This is now on row 562.)
It also removes quite a bit of complexity and some requirements that I never really understood why were necessary. Now it appears they aren't.
This is worth a patch-level version bump, I think.
> Left-recursion improvements.

- pegged/grammar.d
By providing an overload to the grammar function that accepts a parsed "Peg Grammar ParseTree", it allows the grammar to be parsed once and then used in other places outside of just the grammar function.
> Added grammar overload.

- README.md
I added Pegged to run.dlang.io today. This button allows a reader to quickly open the example on run.dlang.io
For convenience: https://run.dlang.io/is/AYKe5x
I also added Pegged to the DUB mini-series for the DTour: https://tour.dlang.org/tour/en/dub/pegged
Any improvements to that page are welcome too.
> Add a button 'run.dlang.io' button

- pegged/parser.d
- pegged/peg.d
- pegged/tester/testerparser.d
Building documentation with `dub build -b docs` or `dub build -b ddox` returned an error due to some mismatched parentheses.
Incidentally this error prevents other projects using Pegged as a dependency to build docs properly.
This commit fixes those issues.
EDIT: version informations:
DUB version 1.9.0, built on May  3 2018
DMD64 D Compiler v2.080.0-dirty
> Fix parenthesis issues blocking documentation generation

- pegged/examples/c.d
> Fix C grammar for identifiers with keyword prefixes

- pegged/peg.d
Here I am introducing the `failEnd` and `failedChild` members of the ParseTree.
Currently pegged discards the longest failed match in the option?, the zeroOrMore* or the oneOrMore+ operators.
Let me illustrate:
```
Thing <- (A B)* C
A <- "abc"
B <- "def"
C <- "ghi"
```
Let us run this grammer on the following input: "abc". It will fail of course and the error message will be `expected "ghi" but found end of line`. This is silly because A did actually correctly match (except it is discarded) and the error ought to be `expected "def" but found end of line.`
This also occurs with the (A B)? or the (A B)+ (after the first match).
Essentially the option, zeroOrMore and the oneOrMore rules eat errors, and that can be problematic if during those rules it actually parsed the longest failing …
> keep track of the longest failed match to improve error messages

- pegged/peg.d
Resolves issue #133 and #204 
toString() now calls failMsg to generate the error code, avoiding soem duplicated code.
failMsg now accepts two optional parameters to allow customize the error message using a delegate function.
> Refactor error reporting

- pegged/peg.d
Override opIndex, opDoller and OpSlice like is suggested in #258 
So `p.children[x].children[y]` could be `p[x][y]` or `p.children[1..$-1]` could be `p[1..$-1]` , etc.
> opIndex, opDollar and opSlice override on ParseTree

- pegged/peg.d
Essentially we never need to keep the discard nodes
> Fixes unittests failure introduced by #272

- makefile
This makes it support ldc, and uses same functional options for all 3 compilers.
Tested on ldc 1.12 (based on dmd 2.082.1), and gdc 8.3.0 (compilation fails with syntax error, because of a feature added in 2.079.1). Options are correct however.
> Make makefile support LDC, and use same options

- pegged/peg.d
Trying to generate a grammar whose PEG syntax is wrong at compile time with pegged `v0.4.5` and DMD `v2.095.0` or `v2.096.1` fails with:
```
./../pegged/peg.d(284,30): Error: static variable `defaultFormatFailMsg` cannot be read at compile time
../../pegged/peg.d(284,30):        called from here: `this.failMsg(cast(string delegate(Position, string, string, const(ParseTree)))defaultFormatFailMsg, "Sucess")`
../../pegged/peg.d(271,40):        called from here: `this.toStringThisNode(allChildrenSuccessful)`
../../pegged/peg.d(266,60):        called from here: `child.toString(tabs ~ (i < this.children.length - 1LU ? " | " : "   "))`
../../pegged/peg.d(257,12):        13 recursive calls to function `toString`
../../pegged/grammar.d(106,75):        called from here: …
```
> Fix defaultFormatFailMsg at compile time

- examples/c/src/pegged/examples/c.d
Identifiers can start with a keyword, e.g. `fortune` starts with `for`. Because `IdentPattern` did not allow for digits, valid identifiers like `auto0` were rejected.
A question not addressed by this is that all identifiers starting with `__` or `_` and uppercase are reserved.
> Recognize keyword-starting identifier correctly

- examples/python/Makefile
- examples/python/dub.json
- examples/python/src/pegged/examples/python.d
Hi,
I tried to add python example, the syntax is taken from:
https://docs.python.org/3/reference/grammar.html
I made minimal modification to use Pegged syntax.
However, the `make test` is still not quite working, and as a Pegged newbie, I cannot figure out how to fix these compilation errors:
```
~/project/contrib/Pegged/examples/python$ make
dub test
Generating test runner configuration 'python-test-library' for 'library' (library).
Performing "unittest" build using /ldc2-1.28.0-linux-x86_64/bin/ldc2 for x86_64.
pegged 0.4.5+commit.5.g913d8dd: building configuration "default"...
python ~master: building configuration "python-test-library"...
../../pegged/peg.d(1842,9): Error: variable `pegged.examples.python.GenericPython!(ParseTree).GenericPython.Python.longest_match!(tuple, group, …
```
> add python example

- examples/python/dub.json
- examples/python/src/pegged/examples/python.d
A couple of fixes:
-- `<-` to `<`
-- https://docs.python.org/3/reference/grammar.html in many places use:
```
','.expression+
```
I'm not sure if this is standard PEG syntax, anyway, translated into
```
((expression ("," expression)*)
```
Actually the grammar is still not working, the parsing output in the unittest is wrong:
```
Running python-test-library 
Python[0, 0][]
+-Python.file[0, 0][]
```
However, I noticed Pegged is really slow, without 'lowmem' it run out of memory (after consume ~32GB); and with lowmem, it took ~5min to build. This make the trial-and-error process to debug very time consuming, esp. considering I'm a Pegged newbie.
I also tried to use the Python library parsimonious to help, and found it's really fast and helpful to identify errors; but unfortunately, due to …
> refine Python grammar

- pegged/peg.d
Apply same fix as in #325.
Fixes #333 ArraySliceError.
> Prevent slicing beyond bounds.

- .github/workflows/d.yaml
- examples/misc/src/pegged/examples/testergrammar.d
- pegged/dev/regenerate.d
- pegged/tester/testerparser.d
Check that generated files were not edited by hand and that parsers were regenerated from their grammars.
> CI test parser regeneration.
